name: Publish Types

on:
  push:
    branches:
      - main

jobs:
  publish-types:
    name: Publish Types Package to OCI Registry
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      # Log in to Azure (test dependency)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PUBLISH_CLIENT_ID }}
          tenant-id: ${{ secrets.PUBLISH_TENANT_ID }}
          subscription-id: ${{ secrets.PUBLISH_SUBSCRIPTION_ID }}

      # Installing ORAS (test dependency)
      - name: Login to OCI Registry using ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.1.0

      # Logging into OCI Registry (test dependency)
      - name: Login to OCI Registry using ORAS
        run: |
          az acr login -t -n ${{ secrets.PUBLISH_REGISTRY_SERVER }} -o tsv --query accessToken | oras login --password-stdin ${{ secrets.PUBLISH_REGISTRY_SERVER }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Publish My Package
        id: publish-types
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require("./scripts/github-actions/publish-az-types.js")
            return await script({
              require,
              registryFqdn: "${{ secrets.PUBLISH_REGISTRY_SERVER }}",
              tags: "0.0.0-alpha+${{ steps.vars.outputs.sha_short	}}",
              core,
            })
