name: Publish OCI Types Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-oci-types-package:
    environment:
      name: test
    permissions:
      id-token: write
      contents: read
    name: Publish Types Package to OCI Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Logging into Azure (publish-az-types.js dependency)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Generate tag for the package based on event type
        id: generate_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=0.0.0-alpha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          else
            echo "tag=0.0.0-alpha-pr${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi
  
      - name: Intall Bicep CLI
        env:
          GH_TOKEN: ${{ github.token }}
        # use the nightly build of the Bicep CLI to publish the resource types provider
        run: bash <(curl -Ls https://aka.ms/bicep/nightly-cli.sh)
      
      - name: test install
        run: ~/.azure/bin/bicep --version
        
      - name: Publish Azure Resource Types
        id: publish-types
        run: ~/.azure/bin/bicep publish-provider ./generated/index.json --target "br:${{ secrets.PUBLISH_REGISTRY_SERVER }}/bicep/providers/az:${{ steps.generate_tag.outputs.tag }}" --force
