name: Ari Test Script

on:
  pull_request:
    branches: [main]

jobs:

  test-oidc-connect:
    environment: test
    permissions:
      id-token: write
      contents: read
    name: "Test OIDC Connect"
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PUBLISH_CLIENT_ID }}
          tenant-id: ${{ secrets.PUBLISH_TENANT_ID }}
          subscription-id: ${{ secrets.PUBLISH_SUBSCRIPTION_ID }}

      - name: "Run az commands"
        run: |
          az account show
          az group list
