name: Ari Test Script

on:
  pull_request:
    branches: [main]

jobs:

  test-oidc-connect:
    environment: test
    permissions:
      id-token: write
      contents: read
    name: "Test OIDC Connect"
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PUBLISH_CLIENT_ID }}
          tenant-id: ${{ secrets.PUBLISH_TENANT_ID }}
          subscription-id: ${{ secrets.PUBLISH_SUBSCRIPTION_ID }}

      - name: "Run az commands"
        run: |
          az account show
          az group list

       # Install ORAS (tests dependency)
      - name: Login to OCI Registry using ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.1.0

      # Log in to OCI Registry (tests dependency)
      - name: Login to OCI Registry using ORAS
        run: |
          az acr login -t -n ${{ secrets.PUBLISH_REGISTRY_SERVER }} -o tsv --query accessToken | oras login --password-stdin ${{ secrets.PUBLISH_REGISTRY_SERVER }}

      - name: Run ORAS version to see if its working
        run: |
          oras repo ls ${{ secrets.PUBLISH_REGISTRY_SERVER }}
